### ISSUE TITLE
v2.2.0: Exceptions when calling certain Faker methods

### ISSUE THREAD

**Issue by bpicode** [datafaker-net/datafaker#1168]
**Describe the bug**
Observed the following exceptions:
* `java.lang.RuntimeException: Unable to resolve #{IDNumber.ssn_valid} directive for FakerContext FakerContext{, locale=SingletonLocale{locale=en}, randomService=net.datafaker.service.RandomService@1}.`
* `java.lang.NoClassDefFoundError: net/datafaker/shaded/curiousoddman/rgxgen/RgxGen`

**To Reproduce**
To reproduce, call Faker as follows
* `(new Faker()).idNumber().valid()`
* `(new Faker()).regexify("[a-z]{6}")`

**Expected behavior**
No exceptions thrown.

**Versions:**
 - JDK: OpenJDK Runtime Environment Corretto-17
 - Faker Version: 2.2.0

**Additional context**
With version 2.1.0 it was still working.

**Comment by snuyanzin** [comment]
Thanks for reporting
yeah, shading of hyphens might be tricky...

the issue is not reproduced in datafaker tests since shading is happening after that
I was able to reproduce it with [datafaker-gen](https://github.com/datafaker-net/datafaker-gen) where datafaker is used a separate lib

after this fix it starts working again
@bpicode could you please double check that this fix also helps with your setup?
https://github.com/datafaker-net/datafaker-gen/actions/runs/8814194154/job/24193516670?pr=9

**Comment by bpicode** [comment]
@snuyanzin How can I check the fix? Should I build this lib with the commit https://github.com/datafaker-net/datafaker/pull/1169/commits/7a5fb07715600ad39e99bf204b3550c18243ea5e locally?

**Comment by snuyanzin** [comment]
yes, currently building it locally and publish to local maven repo (e.g. `mvn clean install`) and then use it as dependency (version `2.2.1-SNAPSHOT`)  seems to be the only way to check

**Comment by bodiam** [comment]
Hi all, thanks for the quick action on this. If this is confirmed to be fixed, happy to release a new version.

**Comment by bpicode** [comment]
Yes I can confirm that this is fixed. Thanks for the quick responses.

**Comment by snuyanzin** [comment]
thanks for checking
yep, i think it make sense to have a bug fix release since this issue makes all expression related functionality non working...
sorry about that
