### ISSUE TITLE
`number_between` for integers returns doubles from time to time

### ISSUE THREAD

**Issue by valfirst** [datafaker-net/datafaker#1463]
**Describe the bug**
This is a regression issue. It's not reproduced on `2.4.11`, but reproduced from time to time on `2.4.2`. Most likely it is caused by this commit: https://github.com/datafaker-net/datafaker/commit/f073184da3b743e4cc0faa05d540196baa99ac89.

**To Reproduce**
```java
import net.datafaker.Faker;

public class Main
{
    public static void main(String[] args)
    {
        Faker faker = new Faker();
        String result = faker.expression("#{number.number_between '1000','1000'}");
        System.out.printf(result);
    }
}
```

**Expected behavior**
The result should be '1000', but it is '1000.0' from time to time.

**Versions:**
 - OS: any
 - JDK: no correlation detected
 - Faker Version: `2.4.2`

**Additional context**
The methods order is preserved when they are returned from class: https://github.com/datafaker-net/datafaker/blob/abdecbc048b2c26c766d91edbf32ff954073f2d4/src/main/java/net/datafaker/service/FakeValuesService.java#L964
But then they are stored in HashMap with unpredictable order: https://github.com/datafaker-net/datafaker/blob/abdecbc048b2c26c766d91edbf32ff954073f2d4/src/main/java/net/datafaker/service/FakeValuesService.java#L966
I see 2 possible solutions:
- rely on method order in the class and use ordered collections to keep sequence - fragile
- improve the algorithm to distinguish double-s vs long-s vs int-s, and search for the method in priority starting from best matching type: e.g. 10 -> int, 10000000000 -> long, 10.0 -> double

**Comment by kingthorin** [comment]
Doubles are numbers right?

**Comment by kingthorin** [comment]
https://github.com/datafaker-net/datafaker/pull/1392

**Comment by kingthorin** [comment]
Ok, so no issue?

**Comment by asolntsev** [comment]
> I mean I guess we (or someone) could introduce `integerBetween`, `longBetween`, `doubleBetween` if that helps.

May I ask why it's needed?
We already have such methods:

```java
int a = faker.number().numberBetween(int, int);
double b = faker.number().numberBetween(double, double);
long c = faker.number().numberBetween(long, long);
```

**Comment by kingthorin** [comment]
I guess it isn't, I hadn't looked 🙄

**Comment by valfirst** [comment]
> > I mean I guess we (or someone) could introduce `integerBetween`, `longBetween`, `doubleBetween` if that helps.
> 
> May I ask why it's needed? We already have such methods:
> 
> ```java
> int a = faker.number().numberBetween(int, int);
> double b = faker.number().numberBetween(double, double);
> long c = faker.number().numberBetween(long, long);
> ```

When string representation of expression is evaluated, the incorrect method from this list is invoked from time to time, e.g.: 
```
faker.expression("#{number.number_between '1','10'}");
```
may result in `2.9189383404296914`.
This is a regression in `2.4.2`.

**Comment by snuyanzin** [comment]
i guess the reason is changed behavior
logically it might be still correct since a number is between boundaries 
however it might be a breaking change.

The root cause seems to be that
expressions like 
```java
faker.expression("#{number.number_between '1','10'}");
```
under the hood use reflections. So from this `#{number.number_between '1','10'}` it finds a class and a method based on name and a number of args.

The problem is that if before the mentioned change there were 2 methods matching this like 
```java
int a = faker.number().numberBetween(int, int);
long c = faker.number().numberBetween(long, long);
```

now there is a new one since it doesn't check for types.

IMHO it seems to be a breaking change.

**Comment by bodiam** [comment]
Hi all, I did this on purpose since decimals are numbers too, and the contract for the original method was never integers only. If you want that, make a new method which returns whole numbers only. 

I don't see this as a breaking change, though I can see that this might give some unexpected results, but the behavior of the method was never well defined. 

I don't want to introduce a method which has a deviating name for doubles, but I see no reason why number_between (1,4) could not return 2.5

**Comment by valfirst** [comment]
> improve the algorithm to distinguish double-s vs long-s vs int-s, and search for the method in priority starting from best matching type: e.g. 10 -> int, 10000000000 -> long, 10.0 -> double

@bodiam what about this proposal?

**Comment by snuyanzin** [comment]
>I don't see this as a breaking change,

here it is a definition of breaking change from wiktionary https://en.wiktionary.org/wiki/breaking_change
> A change in one part of a [software](https://en.wiktionary.org/wiki/software#English) system that potentially causes other components to [fail](https://en.wiktionary.org/wiki/fail#English); occurs most often in shared [libraries](https://en.wiktionary.org/wiki/library#English) of [code](https://en.wiktionary.org/wiki/code#English) used by multiple [applications](https://en.wiktionary.org/wiki/application#English).

and it matches this case

regarding 
>improve the algorithm to distinguish double-s vs long-s vs int-s, and search for the method in priority starting from best matching type: e.g. 10 -> int, 10000000000 -> long, 10.0 -> double

I have a slightly different suggestion. 
Need to go into code to be more precised however IIRC the args should be parsed first before passing to the method. It means that if we parse them then we know there type. If we know there type we could use this knowledge to filter the required method

**Comment by bodiam** [comment]
> > improve the algorithm to distinguish double-s vs long-s vs int-s, and search for the method in priority starting from best matching type: e.g. 10 -> int, [10000000000](tel:10000000000) -> long, 10.0 -> double
> 
> @bodiam what about this proposal?

Sorry, I don't understand what you mean.

**Comment by bodiam** [comment]
> > I don't see this as a breaking change,
> 
> here it is a definition of breaking change from wiktionary https://en.wiktionary.org/wiki/breaking_change
> 
> > A change in one part of a [software](https://en.wiktionary.org/wiki/software#English) system that potentially causes other components to [fail](https://en.wiktionary.org/wiki/fail#English); occurs most often in shared [libraries](https://en.wiktionary.org/wiki/library#English) of [code](https://en.wiktionary.org/wiki/code#English) used by multiple [applications](https://en.wiktionary.org/wiki/application#English).
> 
> and it matches this case.

It's the most ambiguous definition I've seen. If we add a method to Datafaker, and my system is depending on the number of methods in Datafaker, so it "potentially" causes other components to fail, it would make adding a method a breaking change. 

The method here was always supposed to return numbers. It's still returning numbers. So, no breaking change. Maybe the original method was returning only numbers between -100 and +100, and I changed it to -1000 to +1000. It might break a system here or there, but that's not really the fault of Datafaker: it's a bad idea to depend on the implementation of the method instead of the contract, and no contracts have changed.

> 
> Moreover we have this case covered in tests, however seems while review it was missed that the tests were changed as well. So the behavior of expression was well defined in tests in this line [f073184#diff-d867ad35f7992df4ac0dfe8d5e0195ec106d0cf5dd951c36a56fc3022faddc8eR165](https://github.com/datafaker-net/datafaker/commit/f073184da3b743e4cc0faa05d540196baa99ac89#diff-d867ad35f7992df4ac0dfe8d5e0195ec106d0cf5dd951c36a56fc3022faddc8eR165).
> 

I don't see what is missed here. I explicitly added this. I'm really surprised we're having a discussion on what a number is really. I was hoping we could all agree that 1.5 is a number, just as 2 or 3 is, so really not sure why we're having this discussion.

**Comment by bodiam** [comment]
> faker.expression("#{number.number_between '1','10'}");

Introduce `faker.expression("#{number.whole_number_between '1','10'}");` instead?

**Comment by valfirst** [comment]
what about `faker.expression("#{number.number_between '1','10', '2'}");` <- where '2' is the
precision - the number of digits after the floating point?
in the same way for java:
```java
int i = faker.number().numberBetween(int, int);
double d1 = faker.number().numberBetween(double, double);
double d2 = faker.number().numberBetween(double, double, int);
long l = faker.number().numberBetween(long, long);
```

**Comment by snuyanzin** [comment]
how do you make it returning only 2 digits for `double` ?

**Comment by kingthorin** [comment]
If you're going to do something like that I think you may as well use the regexify functionality.

**Comment by valfirst** [comment]
> how do you make it returning only 2 digits for `double` ?

For now `faker.expression("#{number.number_between '1','10'}");` may generate the number like `2.9189383404296914`, while with precision '2' it could be `2.91`

**Comment by valfirst** [comment]
> @valfirst
If you're going to do something like that I think you may as well use the regexify functionality.

could you please share example, how `regexify` can be used to generate a number from 1 to 100?

**Comment by snuyanzin** [comment]
>For now faker.expression("#{number.number_between '1','10'}"); may generate the number like 2.9189383404296914, while with precision '2' it could be 2.91

`faker.expression` just invokes the method it found in expression and returns the `toString` result. It doesn't have any knowledge about it's return type of the method it invokes since for different use cases it could be different.

**Comment by kingthorin** [comment]
> could you please share example, how `regexify` can be used to generate a number from 1 to 100?

Sorry I should have said numerify not regexify, but anyway:

```java
    @RepeatedTest(100)
    void temp() {
        System.out.println(faker.numerify("#".repeat(faker.number().numberBetween(1, 3))));
    }
```

If you want to ensure no leading zero, or simply zero:

```java
    @RepeatedTest(100)
    void temp() {
        int digits = faker.number().numberBetween(1,34);
        String pattern = digits == 1 ? "Ø" : "Ø" + "#".repeat(digits - 1);
        System.out.println(faker.numerify(pattern));
    }
```

**Comment by snuyanzin** [comment]
@valfirst 
I think this should made every participant of this issue discussion more or less happy
https://github.com/datafaker-net/datafaker/pull/1465

**Comment by valfirst** [comment]
> @valfirst I think this should made every participant of this issue discussion more or less happy #1465
> 
> can you please test your case with this update?

I've tested the changes locally, everything works fine now. I greatly appreciate your help and dedication.

**Comment by bodiam** [comment]
I'm not convinced about this. I haven't changed my fact that 1.5 is a number between 1 and 2. This PR is not changing that. 

I forgot why I added it for the expression test, it actually may have been a side effect  of adding the double method, so I doubt it's going to affect me (or anyone) in reality. 

So I'll go with the majority vote :)

**Comment by snuyanzin** [comment]
>I haven't changed my fact that 1.5 is a number between 1 and 2.

nobody was trying to make you changing this

however apart from regular math there is also type system (not only java specific)
if you try to execute the code
```java
for (int i = 0; i < $PUT_YOUR_NUMBER_HERE$; i++) {
    System.out.println(faker.number().numberBetween(1, 2));
}
```
you will never get `1.5` or any other number with fractional part
this happens because of Narrowing Primitive Conversion mentioned in chapter 5 of JLS

If you want to have anything with fractional part you need to say explicitly that your args are double like 
```java
for (int i = 0; i < $PUT_YOUR_NUMBER_HERE$; i++) {
    System.out.println(faker.number().numberBetween(1.0, 2));
}
```

similar approach is applied in this PR
