### ISSUE TITLE
CreditCardType is not accessible although it's used as a parameter to a public method

### ISSUE THREAD

**Issue by SaraMahdy** [datafaker-net/datafaker#860]
**Describe the bug**
CreditCardType enum has recently changed to be internal instead of external. This breaks any code that either uses the enum directly or the public method creditCard(CreditCardType creditCardType).

**Expected behavior**
CreditCardType be exposed to public.

**Comment by snuyanzin** [comment]
yes, that is not good
however could you please elaborate more what is the use case to use this method while using datafaker?
I thought `creditCard()` should be ebough

**Comment by bodiam** [comment]
I haven't checked yet, but does this affect both the 1.x and 2.x versions?

**Comment by SaraMahdy** [comment]
It affects only 2.x versions

**Comment by snuyanzin** [comment]
looks like only 2.x
the fastest way for users is to create a class (in same package like `net.datafaker.providers.base.<yourClassnameHere>`) in extending `Finance`.
Since `CreditCardType` has package private access it will be possible to access `CreditCardType` from this new class.

So far it could be considered as a WA

**Comment by bodiam** [comment]
Interesting: I'm sure I did that that change for a reason, I just don't remember what the reason was. I remember that I did it because all the classes in that package are Providers, except for CreditCardType. 

If I make the enum public, but keep it inside the Finance class, would that work for you? (I think the import will change a little, but that's it)

**Comment by bodiam** [comment]
The same issue seemed to affect Compass. I fixed both of them here:

https://github.com/datafaker-net/datafaker/pull/861

I'll merge them. After the merge, could you try out the 2.0.1-SNAPSHOT version? If that works well, I'll release it.

**Comment by redhell** [comment]
Works for me 👍

**Comment by kingthorin** [comment]
Thanks for confirming.

**Comment by bodiam** [comment]
Thanks, I'll make a new release tomorrow!

**Comment by bodiam** [comment]
2.0.1 has been released, which should fix this issue. Thanks again for reporting and testing it!
